# Generated by Django 2.0.5 on 2018-05-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaccount', models.CharField(max_length=15)),
                ('apwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ggname', models.CharField(max_length=20)),
                ('gaddtime', models.DateTimeField(auto_now_add=True)),
                ('gisdelete', models.NullBooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='auser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Guest'),
        ),
    ]
