# Generated by Django 2.0.5 on 2018-05-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180527_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=30)),
                ('acontent', models.TextField()),
                ('aaddtime', models.TimeField(auto_now_add=True)),
                ('astatus', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acontent', models.TextField(max_length=500)),
                ('aaddtime', models.TimeField(auto_now_add=True)),
                ('apid', models.IntegerField(default=0)),
                ('aisdelete', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Publishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=30)),
                ('ptype', models.IntegerField(default=1)),
                ('pcontent', models.TextField()),
                ('pclick', models.IntegerField(default=0)),
                ('paddtime', models.TimeField(auto_now_add=True)),
                ('pisdelete', models.NullBooleanField(default=None)),
                ('pisTop', models.IntegerField(default=0)),
                ('pdetest', models.IntegerField(default=0)),
                ('pstatus', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='auser',
        ),
        migrations.AddField(
            model_name='guest',
            name='gaccount',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='gemail',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='gpwd',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='gaddtime',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='gisdelete',
            field=models.NullBooleanField(default=None),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='publishment',
            name='pguest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Guest'),
        ),
        migrations.AddField(
            model_name='answer',
            name='aguest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Guest'),
        ),
        migrations.AddField(
            model_name='answer',
            name='aobject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Publishment'),
        ),
    ]
