# Generated by Django 2.0.5 on 2018-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180528_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nname', models.CharField(max_length=10)),
                ('nsort', models.IntegerField(default=1)),
                ('nlink', models.CharField(max_length=50)),
                ('naddtime', models.DateTimeField(auto_now_add=True)),
                ('nstatus', models.IntegerField(default=1)),
                ('nisdelete', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='aaddtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='aaddtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='gaddtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='publishment',
            name='paddtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
