# Generated by Django 2.0.5 on 2018-05-29 09:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180528_1511'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='nav',
            managers=[
                ('n_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='guest',
            name='gname',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='nav',
            name='nname',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
