# Generated by Django 2.0.5 on 2018-05-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180529_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='ggender',
            field=models.NullBooleanField(default=None),
        ),
    ]
