# Generated by Django 2.0.5 on 2018-05-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_guest_ggender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='gaccount',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
