# Generated by Django 2.0.5 on 2018-05-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180530_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='aguest',
        ),
        migrations.RemoveField(
            model_name='publishment',
            name='pguest',
        ),
    ]
