# Generated by Django 2.0.5 on 2018-05-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180530_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='aguest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Guest'),
        ),
        migrations.AddField(
            model_name='publishment',
            name='pguest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Guest'),
        ),
    ]
