# Generated by Django 2.0.5 on 2018-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180530_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='gphoto',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
