# Generated by Django 2.0.5 on 2018-05-31 07:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_guest_gphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishment',
            name='pcontent',
            field=tinymce.models.HTMLField(),
        ),
    ]
