# Generated by Django 2.0.5 on 2018-06-01 12:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180531_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Comment',
        ),
        migrations.AlterModelManagers(
            name='publishment',
            managers=[
                ('p_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='aaddtime',
            new_name='caddtime',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='acontent',
            new_name='ccontent',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='aguest',
            new_name='cguest',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='aisdelete',
            new_name='cisdelete',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='aobject',
            new_name='cobject',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='apid',
            new_name='cpid',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='nlink',
        ),
    ]
