# Generated by Django 2.0.5 on 2018-06-02 02:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180601_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ccontent',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='crcontent',
            field=tinymce.models.HTMLField(),
        ),
    ]
